### PR TITLE
Update Microsoft.CodeAnalysis to 2.1.0 

### PR DESCRIPTION
**Pull request by Nate-Wilkins**
A first attempt at converting over to Microsoft.CodeAnalysis v2.1.0 

I'm going to be cleaning up the code a bit but I just wanted to get the PR out there to make sure this was okay. 

I'll be getting rid of the integrated interpolation in favor of the language interpolation along with fixing a few tests that didn't conform.
I'll also be updating the README and any other documentation that was impacted ASAP

### CODE REVIEW

**Comment by yevhen** [comment]
Love it!

I was hesitating to remove support for custom string interpolation syntax (the one which doesn't require $ sign) but I think it's ok to do it for major version release. Will list as a breaking change.

P.S. We can even create a one-time conversion tool using current version of Nake to convert "{{var}}" strings to $"{{var}}" ))

**Comment by yevhen** [comment]
Reagrding AppVeyor build failure - NuGet tool need to be updated to latest version. Should fix CI build.

**Comment by yevhen** [comment]
@Nate-Wilkins You need to update NuGet.exe in Tools folder to latest. That should fix CI build on AppVeyour.

**Comment by Nate-Wilkins** [comment]
Updated! I haven't checked it in though. Fixing up the `FS` class module and removing the MSBuild libraries. Also writing down all the breaking api changes.

**Comment by yevhen** [comment]
@Nate-Wilkins what is your tab size setting? I see a lot of spacing changes in files.

**Comment by Nate-Wilkins** [comment]
Woops, yeah changing that to 4spaces instead of tabs myb.

**Pull request closed without merging**
